### ISSUE TITLE
Reject PRs with conflicts

### ISSUE THREAD

**Issue by lugray** [Shopify/shipit-engine#748] opened 2017-11-06 14:53 UTC
If a PR in the merge queue has conflicts with master, it shouldn't sit there silently, it should be removed from the merge queue, and the author notified.

**Comment by byroot** [comment] 2017-11-06 14:54
Conflict as in merge conflict?

**Comment by lugray** [comment] 2017-11-06 14:55
Yes.

**Comment by byroot** [comment] 2017-11-06 14:57
Closing as duplicate of: https://github.com/Shopify/shipit-engine/issues/749

**Closed by byroot** 2017-11-06 14:57 UTC
