### ISSUE TITLE
Merge queue revalidate_after send the uses back at the end of the queue

### ISSUE THREAD

**Issue by tjoyal** [Shopify/shipit-engine#766] opened 2018-03-16 18:08 UTC
Waiting 60min to be asked if you are still staring to your screen to be sent at the end of the line after those that just arrived is not making me very happy.

If that something fixable?

**Comment by casperisfine** [comment] 2018-03-19 10:00
[Pull requests are ordered by `merge_requested_at asc` to be merged](https://github.com/Shopify/shipit-engine/blob/ba0b88e19e45331565731035adc6a3c2f2f3ae7b/app/models/shipit/pull_request.rb#L50), and [when you revalidate `merge_requested_at` is not modified](https://github.com/Shopify/shipit-engine/blob/ba0b88e19e45331565731035adc6a3c2f2f3ae7b/app/models/shipit/pull_request.rb#L96-L98). 

So the behavior you describe isn't expected.

However it has been reported before: https://github.com/Shopify/shipit-engine/issues/736, so I'm inclined to think there might be a bug or at the very least a poor UX that cause people to de-queue & re-queue instead of actually revalidating.

However all the reports I got so far didn't allow me to figure that out. If you remember which PR it is please open an issue on the private repo with the details so I try to figure out what happened.

**Comment by tjoyal** [comment] 2018-03-19 17:13
Reading some of the code I have a theory:
- 10 in queue, 5 need revalidation
- deploy finish, 5 first are asked to be re-validated and the next 5 gets auto merged

This would give the impression the fist 5 lost their priority?

That would mean either:
- Works as expected
or
- UX need a way to ask for "revalidation" slightly before or at expiry and not when it try to merge it?

**Comment by dylanahsmith** [comment] 2018-03-19 21:15
It does look like MergePullRequestsJob would skip over jobs that need to be revalidated, so I think @tjoyal's theory is right.  However, I have also been seeing the list of pull requests in the merge queue have their enqueued duration get updated to a short time ago after revalidation, so there might be two problems.

Could the pull requests be briefly transitioning to the rejected state then the pending state, which would update the `merge_requested_at` time?  I don't see why else `merge_requested_at` would be changing based on the code, but also nothing stands out as a reason why this would happen.

**Comment by BoGs** [comment] 2018-03-20 15:09
Is anyone looking at this? If not I am happy to.

**Comment by wvanbergen** [comment] 2018-03-20 15:19
Nobody from shipping pipeline is looking at this currently. Feel free to see if you can find the issue and post your findings here.

**Comment by casperisfine** [comment] 2018-03-20 17:13
Actually the problem have been identified already https://github.com/Shopify/shipit/issues/323

However I'm not at my computer today, i was planning to fix this later this week

**Comment by BoGs** [comment] 2018-03-20 18:03
Thoughts on the following workflow (@tjoyal @casperisfine @dylanahsmith)
<assume nothing is locked>
1. I add my PR to the queue and 20 minute countdown starts
2. The deploy finishes so it starts working off the queue (deploys ~30 min) so lets assume its 30 min past
3. It sees the PR and passed 20 minute validation
  * it asks to revalidate but at the same time not ready to merge
  * skips you and removed
4. You revalidate and it re-adds you to the queue

I propose we revalidate at a set interval < `revalidate_after: 20m` (https://github.com/Shopify/shopify/blob/master/shipit.yml#L10). I was going to start with `revalidate_after - 5.minutes` which should update `revalidated_at` and then it will never timeout. Thoughts?

**Comment by tjoyal** [comment] 2018-03-20 18:18
Agree, asking 5min before expiration makes sense as a first step (I wonder if this should also be in shipit.yml). 

Ideally it would be tied to the queue size and how much shipit can merge at the same time so you do not get notified unless you would be part of the next batch, but let's start with a flat few minutes for everyone?

**Comment by dylanahsmith** [comment] 2018-03-20 19:00
Yes, revalidating 5 minutes past expiration would work.

**Comment by casperisfine** [comment] 2018-03-22 10:37
So yes, the core of the problem is that we don't ask for revalidation until the PR could actually be merged.

The original reasoning was to not bother people with notifications because we can't know if the situation will be resolved in 2 minutes or 2 hours.

But the downside as you noticed is that if the queue is big enough, we trigger revalidation for expired requests, and then merge all PR that are still valid, and hence added later to the queue creating this unfair situation.

So yeah the fix is to ask for revalidation a bit before the merge request is expired.

**Comment by casperisfine** [comment] 2018-03-23 15:55
@celsodantas just complained about the same thing:

```
#<Shipit::PullRequest:0x0000562c7a077b58
 id: 24196,
 stack_id: 11,
 number: 149532,
 title: "redacted",
 github_id: 176578784,
 api_url: "redacted",
 state: "open",
 head_id: 1203477,
 mergeable: nil,
 additions: 103,
 deletions: 30,
 merge_status: "pending",
 rejection_reason: nil,
 merge_requested_at: Fri, 23 Mar 2018 15:49:22 UTC +00:00,
 merge_requested_by_id: 54,
 created_at: Thu, 22 Mar 2018 17:48:08 UTC +00:00,
 updated_at: Fri, 23 Mar 2018 15:53:23 UTC +00:00,
 branch: "redacted",
 revalidated_at: Fri, 23 Mar 2018 15:49:22 UTC +00:00,
 merged_at: nil,
 base_ref: "master",
 base_commit_id: 1203426>
```

So something must indeed bump the `merge_requested_at`, I'll try to figure out what.

**Comment by celsodantas** [comment] 2018-03-23 15:59
From what I see, I was removed from the queue and after pressing the "Yes ship it!" on slack, I'm put back into the queue, this time at the end of it.

I checked that by visiting https://shipit.shopify.io/shopify/shopify/production/pull_requests before pressing the "Yes ship it!" on slack.

The same issue happened with other ppl in my team today and yesterday.

**Comment by casperisfine** [comment] 2018-03-23 16:06
I don't get it, we have a test to specifically ensure this doesn't happen: https://github.com/Shopify/shipit-engine/blob/49dc68b16029935b65aa0eee339ae900901e9bff/test/models/pull_request_test.rb#L46-L53

I'll dig more, but I might need to add logging to figure out what is happening.

**Comment by casperisfine** [comment] 2018-03-23 16:36
So I've tried to reproduce on another stack, using the API directly, it works as expected.

So whatever is bumping the `merged_requested_at` is not the revalidation.

There must be something canceling the merge request before the user have time to reconfirm, which cause the `merge_requested_at` to be reset.

Still no clue what at this point.

**Comment by casperisfine** [comment] 2018-03-23 16:55
I've added some logging in https://github.com/Shopify/shipit-engine/commit/ca5d71e0402598aacd49486d55f7a0161e8c6390

Please let me know of further occurrences in a private issue so I can try to make sense of this.

**Comment by celsodantas** [comment] 2018-03-23 17:44
this just happened to me twice in a row now.

Same thing happened for 2 PRs (at the same time). I was no longer in the queue by the time I get the spy asking for me to confirm that I want to ship it. So 

I've never seen the `Confirm` button on the queue list for my PRs in https://shipit.shopify.io/shopify/shopify/production/pull_requests . I've seen it for other people, but never for me.

**Comment by celsodantas** [comment] 2018-03-23 17:55
correction, I got pinged by spy again (for those same 2 PRs) and I saw the `Confirm` button on my entry. Pressed confirm for both on the queue page and it worked.

Have no idea if something changed. ¯\\_(ツ)\_/¯

**Comment by lmawarid** [comment] 2018-03-23 19:39
👋Hey all, I noticed that when I click the `Confirm` button on Shipit, it does not requeue my PR. However, before that I clicked the `Yes, ship it` button through `spy` and it sent my PR at the back of the line. Could this possibly be a spy issue?

**Comment by casperisfine** [comment] 2018-03-26 12:52
I've identified the root cause. It's not due to Shipit itself but to our Slack integration.

I'll report my finding there.

**Closed by casperisfine** 2018-03-26 12:52 UTC
