### ISSUE TITLE
Feature Request: Allow updating a stack via the API

### ISSUE THREAD

**Issue by dalehamel** [Shopify/shipit-engine#1075] opened 2020-05-28 18:57 UTC
I would like to be able to update a stack with an API user, so that an API client is able to do the equivalent of clicking "Enable Continuous Integration" on a stack.

I am able to get a stack via the API, but there is no endpoint that allows the API to post to a stack to update "continuous_deployment", which defaults to false.

I'm not the greatest Rails expert, but my understanding is we would need:

```
post '/' => 'stacks#update'
```

In the router here:

https://github.com/Shopify/shipit-engine/blob/master/config/routes.rb#L18-L20

In order for this to work.

Is there a philosophical reason why updating stacks via the API is not allowed? I'd really like to have continuous deployment enabled on the stacks that I create when I provision a service, without requiring user interaction to do so.

**Comment by byroot** [comment] 2020-05-28 19:03
> Is there a philosophical reason why updating stacks via the API is not allowed?

No. I'd need to dig the history, but I'm pretty sure that when I implemented the API there was simply nothing, or close to nothing, to update on stacks. 

Some properties are immutable by design (org, repo, branch, environment), but enabling continuous delivery should be possible.

That change is trivial to make, I can slam it together tomorrow if you want.

**Comment by dalehamel** [comment] 2020-05-28 19:05
> That change is trivial to make, I can slap it together tomorrow if you want.

@byroot that would be really helpful! you'll certainly be faster than me, if you're able to do so tomorrow i'd be very appreciative! Thanks

**Comment by casperisfine** [comment] 2020-05-28 19:36
Actually I had some time. 

Fixed in 6a881978d2aea6d3ce566c99200b1f5c3654be13

**Closed by casperisfine** 2020-05-28 19:36 UTC

**Comment by dalehamel** [comment] 2020-05-28 20:11
thanks @casperisfine / @byroot !
