### ISSUE TITLE
Shipit fails to respect HTTPS as an outbound redirect_uri

### ISSUE THREAD

**Issue by xLegoz** [Shopify/shipit-engine#684] opened 2017-04-03 22:23 UTC
I currently have Shipit set up behind Cloudflare's HTTPS, with HTTP redirecting and HSTS. I'm unsure if this was caused by a recent upgrade I did to Shipit or just changing the Github auth callback without remembering. Currently
`.env`
```bash
SHIPIT_HOST=https://shipit.mydomain.com/
HOST=https://shipit.mydomain.com/
```
`Github authorization callback setting`
```
https://shipit.mydomain.com/github/auth/github/callback
```

And this causes as `redirect_uri_mismatch` due to Github being told to redirect to `http`and not `https`. The solution was to change the Github registered callback to be `http://` which took awhile to figure out.

**Comment by byroot** [comment] 2017-04-04 06:58
So I might be wrong, but from you description it sounds like the request from cloudflare to your server is in HTTP, and that the `X-Forwarded-Proto` header is either not sent of not taken into account.

Do you have an nginx between your cloudflare and shipit? If so you have to tell it to trust that header when it comes from CloudFlare.

Also I suggest you set `config.force_ssl = true` in your Rails app. That way you'll more easily spot the root cause.

Anyway, I don't mind helping you debugging this, but AFAICT it's an issue with your reverse proxy setup, not a Shipit issue, so I'll close it. Feel free to post further and I'll help you if I can.

**Closed by byroot** 2017-04-04 06:58 UTC
